Improve nmcli-cli-autoconnect-list and nmcli-cli-autoconnect-set

diff --git a/nmcli-cli-autoconnect-list b/nmcli-cli-autoconnect-list
--- a/nmcli-cli-autoconnect-list
+++ b/nmcli-cli-autoconnect-list
@@ -2,32 +2,41 @@
 #
 # nmcli-cli-autoconnect-list
 
-ON_OFF=$1
-
-if [[ -z "${ON_OFF}" ]]; then
+usage() {
     cat << _EOF_
 Usage:
 
     $0 on|off
 
-    EXAMPLES
-
+    Examples:
         $0 off
         $0 on
 
 _EOF_
-    exit 1
-fi
+}
 
-if [[ "${ON_OFF}" = on ]]; then
-    ON_OFF="yes"
-elif [[ "${ON_OFF}" = off ]]; then
-    ON_OFF="no"
-else
-    echo "Error: option invalid: ${ON_OFF}"
-    exit 1
-fi
+autoconnect_list() {
+    ON_OFF=${1:-}
 
-# Bond: Find ONBOOT interfaces
-grep "^ONBOOT=${ON_OFF}" /etc/sysconfig/network-scripts/ifcfg-* | cut -d':' -f 1 | sed 's|.*/ifcfg-||g'
+    if [[ "${ON_OFF}" = on ]]; then
+        ON_OFF="yes"
+    elif [[ "${ON_OFF}" = off ]]; then
+        ON_OFF="no"
+    else
+        echo "Error: option \"${ON_OFF}\" is invalid."
+        exit 1
+    fi
+
+    # list
+    grep "^ONBOOT=${ON_OFF}" /etc/sysconfig/network-scripts/ifcfg-* | cut -d':' -f 1 | sed 's|.*/ifcfg-||g'
+}
+
+# Main
+main() {
+    [[ $# -le 0 ]] && usage && exit 1
+
+    autoconnect_list "${@}"
+}
+
+[[ ${#BASH_SOURCE[@]} = 1 ]] && main "${@}"
 
diff --git a/nmcli-cli-autoconnect-set b/nmcli-cli-autoconnect-set
--- a/nmcli-cli-autoconnect-set
+++ b/nmcli-cli-autoconnect-set
@@ -2,33 +2,86 @@
 #
 # nmcli-cli-autoconnect-set
 
-IF_NAME=$1
-ON_OFF=${2}
+ECHO_OR_EXECUTE="echo"
 
-if [[ -z "${ON_OFF}" ]]; then
+usage() {
     cat << _EOF_
 Usage:
 
-    $0 IF_NAME ON|OFF
+    $0 [-n] [-x] IF_NAME ON|OFF
 
-    EXAMPLES
+    Options:
+        -n No interface check (Default: check interface)
+        -x Run command (Default: echo only)
 
+    Examples:
         $0 eno1 off
         $0 bond1 on
 
 _EOF_
-    exit 1
-fi
+}
 
-# Check interface
-nmcli connection show "${IF_NAME}" > /dev/null 2>&1
-RET=$?
-if [[ ${RET} -ne 0 ]]; then
-    echo "Error: Interface ${IF_NAME} not found."
-    exit 1
-fi
+check() {
+    local IF_NAME=${1:-}
 
-# auutoconnect
-echo nmcli connection modify \"${IF_NAME}\" connection.autoconnect \"${ON_OFF}\"
-# nmcli connection modify "${IF_NAME}" connection.autoconnect "${ON_OFF}"
+    # Check interface
+    nmcli connection show "${IF_NAME}" > /dev/null 2>&1
+    RET=$?
+    if [[ ${RET} -ne 0 ]]; then
+        echo "Error: Target interface \"${IF_NAME}\" not found."
+        exit 1
+    fi
+}
+
+echo_or_execute() {
+    if [[ -z "${ECHO_OR_EXECUTE}" ]]; then
+        echo "Applying: ${@}"
+        eval ${@}
+    else
+        ${ECHO_OR_EXECUTE} ${@}
+    fi
+}
+
+autoconnect_set() {
+    local IF_NAME=${1:-}
+    local ON_OFF=${2:-}
+
+    echo_or_execute nmcli connection modify \"${IF_NAME}\" connection.autoconnect \"${ON_OFF}\"
+}
+
+# Main
+main() {
+    local NO_CHECK="no"
+    while getopts nxh OPT; do
+        case "${OPT}" in
+            "n" )
+                NO_CHECK="yes" ;;
+            "x" )
+                ECHO_OR_EXECUTE="" ;;
+            "h" )
+                usage
+                exit 0
+                ;;
+            * )
+                usage
+                exit 1
+                ;;
+        esac
+    done
+    shift $((OPTIND - 1))
+
+    [[ $# -le 1 ]] && usage && exit 1
+
+    if [[ "${NO_CHECK}" = "no" ]]; then
+        check "${@}"
+    fi
+
+    if [[ "${ECHO_OR_EXECUTE}" = "echo" ]]; then
+        echo "# ${ECHO_OR_EXECUTE} only."
+    fi
+
+    autoconnect_set "${@}"
+}
+
+[[ ${#BASH_SOURCE[@]} = 1 ]] && main "${@}"
 
