Improve check

diff --git a/nmcli-cli-bond-add b/nmcli-cli-bond-add
--- a/nmcli-cli-bond-add
+++ b/nmcli-cli-bond-add
@@ -2,16 +2,16 @@
 #
 # nmcli-tool-bond-add
 
-BOND_NAME=$1
-BOND_SLAVE1=$2
-BOND_SLAVE2=$3
+BOND_IF_NAME=$1
+IF_SLAVE1=$2
+IF_SLAVE2=$3
 BOND_OPTIONS=$4
 
 if [[ -z "${BOND_OPTIONS}" ]]; then
     cat << _EOF_
 Usage:
 
-    $0 NEW_BOND_NAME SLAVE1 SLAVE2 BOND_OPTIONS
+    $0 NEW_BOND_IF_NAME IF_SLAVE1 IF_SLAVE2 BOND_OPTIONS
 
     EXAMPLES
 
@@ -22,43 +22,51 @@ _EOF_
     exit 1
 fi
 
+# Check new bond interface
+nmcli connection show "${BOND_IF_NAME}" > /dev/null 2>&1
+RET=$?
+if [[ ${RET} -eq 0 ]]; then
+    echo "Error: Interface ${BOND_IF_NAME} already exists."
+    exit 1
+fi
+
 # Check interface: Slave 1
-nmcli connection show "${BOND_SLAVE1}" > /dev/null 2>&1
+nmcli connection show "${IF_SLAVE1}" > /dev/null 2>&1
 RET=$?
 if [[ ${RET} -ne 0 ]]; then
-    echo "Error: Interface ${BOND_SLAVE1} not found."
+    echo "Error: Interface ${IF_SLAVE1} not found."
     exit 1
 fi
 
 # Check interface: Slave 2
-nmcli connection show "${BOND_SLAVE2}" > /dev/null 2>&1
+nmcli connection show "${IF_SLAVE2}" > /dev/null 2>&1
 RET=$?
 if [[ ${RET} -ne 0 ]]; then
-    echo "Error: Interface ${BOND_SLAVE2} not found."
+    echo "Error: Interface ${IF_SLAVE2} not found."
     exit 1
 fi
 
 # Bonding
-echo nmcli connection add type bond autoconnect yes con-name \"${BOND_NAME}\" ifname \"${BOND_NAME}\"
-# nmcli connection add type bond autoconnect yes con-name "${BOND_NAME}" ifname "${BOND_NAME}"
+echo nmcli connection add type bond autoconnect yes con-name \"${BOND_IF_NAME}\" ifname \"${BOND_IF_NAME}\"
+# nmcli connection add type bond autoconnect yes con-name "${BOND_IF_NAME}" ifname "${BOND_IF_NAME}"
 
 # Slave 1
-echo nmcli connection add type bond-slave autoconnect yes ifname \"${BOND_SLAVE1}\" master \"${BOND_NAME}\"
-# nmcli connection add type bond-slave autoconnect yes ifname "${BOND_SLAVE1}" master "${BOND_NAME}"
+echo nmcli connection add type bond-slave autoconnect yes ifname \"${IF_SLAVE1}\" master \"${BOND_IF_NAME}\"
+# nmcli connection add type bond-slave autoconnect yes ifname "${IF_SLAVE1}" master "${BOND_IF_NAME}"
 
 # Slave 2
-echo nmcli connection add type bond-slave autoconnect yes ifname \"${BOND_SLAVE2}\" master \"${BOND_NAME}\"
-# nmcli connection add type bond-slave autoconnect yes ifname "${BOND_SLAVE2}" master "${BOND_NAME}"
+echo nmcli connection add type bond-slave autoconnect yes ifname \"${IF_SLAVE2}\" master \"${BOND_IF_NAME}\"
+# nmcli connection add type bond-slave autoconnect yes ifname "${IF_SLAVE2}" master "${BOND_IF_NAME}"
 
 # Bonding Options
-echo nmcli connection modify \"${BOND_NAME}\" bond.options \"${BOND_OPTIONS}\"
-# nmcli connection modify "${BOND_NAME}" bond.options "${BOND_OPTIONS}"
+echo nmcli connection modify \"${BOND_IF_NAME}\" bond.options \"${BOND_OPTIONS}\"
+# nmcli connection modify "${BOND_IF_NAME}" bond.options "${BOND_OPTIONS}"
 
 # autoconnect no: Slave 1
-echo nmcli connection modify \"${BOND_SLAVE1}\" connection.autoconnect no
-# nmcli connection modify "${BOND_SLAVE1}" connection.autoconnect no
+echo nmcli connection modify \"${IF_SLAVE1}\" connection.autoconnect no
+# nmcli connection modify "${IF_SLAVE1}" connection.autoconnect no
 
 # autoconnect no: Slave 2
-echo nmcli connection modify \"${BOND_SLAVE2}\" connection.autoconnect no
-# nmcli connection modify "${BOND_SLAVE2}" connection.autoconnect no
+echo nmcli connection modify \"${IF_SLAVE2}\" connection.autoconnect no
+# nmcli connection modify "${IF_SLAVE2}" connection.autoconnect no
 
diff --git a/nmcli-cli-bridge-add b/nmcli-cli-bridge-add
--- a/nmcli-cli-bridge-add
+++ b/nmcli-cli-bridge-add
@@ -2,14 +2,14 @@
 #
 # nmcli-tool-bridge-add
 
-BRDIGE_NAME=$1
-BRDIGE_SLAVE=$2
+BRDIGE_IF_NAME=$1
+IF_SLAVE=$2
 
-if [[ -z "${BRDIGE_SLAVE}" ]]; then
+if [[ -z "${IF_SLAVE}" ]]; then
     cat << _EOF_
 Usage:
 
-    $0 NEW_BRDIGE_NAME SLAVE_NAME
+    $0 NEW_BRDIGE_IF_NAME IF_SLAVE
 
     EXAMPLES
 
@@ -20,20 +20,28 @@ _EOF_
     exit 1
 fi
 
-# Check interface: Slave 1
-nmcli connection show "${BRDIGE_SLAVE}" > /dev/null 2>&1
+# Check new bridge interface
+nmcli connection show "${BRDIGE_IF_NAME}" > /dev/null 2>&1
+RET=$?
+if [[ ${RET} -eq 0 ]]; then
+    echo "Error: Interface ${BRDIGE_IF_NAME} already exists."
+    exit 1
+fi
+
+# Check interface: Slave
+nmcli connection show "${IF_SLAVE}" > /dev/null 2>&1
 RET=$?
 if [[ ${RET} -ne 0 ]]; then
-    echo "Error: Interface ${BRDIGE_SLAVE} not found."
+    echo "Error: Interface ${IF_SLAVE} not found."
     exit 1
 fi
 
 # Bridge: STP: No, Forward Delay: 0
-echo nmcli connection add type bridge autoconnect yes bridge.stp no bridge.forward-delay 0 con-name \"${BRDIGE_NAME}\" ifname \"${BRDIGE_NAME}\"
-# nmcli connection add type bridge autoconnect yes bridge.stp no bridge.forward-delay 0 nocon-name "${BRDIGE_NAME}" ifname "${BRDIGE_NAME}"
+echo nmcli connection add type bridge autoconnect yes bridge.stp no bridge.forward-delay 0 con-name \"${BRDIGE_IF_NAME}\" ifname \"${BRDIGE_IF_NAME}\"
+# nmcli connection add type bridge autoconnect yes bridge.stp no bridge.forward-delay 0 nocon-name "${BRDIGE_IF_NAME}" ifname "${BRDIGE_IF_NAME}"
 
 # Slave
-echo nmcli connection modify \"${BRDIGE_SLAVE}\" connection.slave-type bridge connection.master \"${BRDIGE_NAME}\"
+echo nmcli connection modify \"${IF_SLAVE}\" connection.slave-type bridge connection.master \"${BRDIGE_IF_NAME}\"
 
 # Option: IP
 echo
diff --git a/nmcli-cli-vlan-add b/nmcli-cli-vlan-add
--- a/nmcli-cli-vlan-add
+++ b/nmcli-cli-vlan-add
@@ -2,24 +2,30 @@
 #
 # nmcli-tool-vlan-add
 
-IF_NAME=$1
-VLAN_ID=$2
-VLAN_IF_NAME=${3:-$IF_NAME.$VLAN_ID}
+VLAN_IF_NAME=$1
+IF_NAME=$2
+VLAN_ID=$3
 
 if [[ -z "${VLAN_ID}" ]]; then
     cat << _EOF_
 Usage:
 
-    $0 IF_NAME VLAN_ID [VLAN_IF_NAME]
+    $0 VLAN_IF_NAME IF_NAME VLAN_ID
 
     EXAMPLES
 
-        $0 eno1 100
-            -> eno1.100
-        $0 bond1 100 vlan.100
-            -> vlan.100
+        $0 eno1.100 eno1 100
+        $0 vlan.100 bond1 100
 
 _EOF_
+    exit 1
+fi
+
+# Check new vlan interface
+nmcli connection show "${VLAN_IF_NAME}" > /dev/null 2>&1
+RET=$?
+if [[ ${RET} -eq 0 ]]; then
+    echo "Error: Interface ${VLAN_IF_NAME} already exists."
     exit 1
 fi
 
